@host = http://localhost:5185
@email = activity_test_1@test.com
@username = user_1
@password = 123456789
@fullName = Activity Tester
@role = user

# Fill after sign-in:
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Y2UxMGVmYi0xMDM3LTQ1NGUtOWI0MC0zYmQ2Y2NhODljODciLCJ1bmlxdWVfbmFtZSI6IjRjZTEwZWZiLTEwMzctNDU0ZS05YjQwLTNiZDZjY2E4OWM4NyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJuYmYiOjE3NzMyMTEyNjksImV4cCI6MTc3MzIxNDg2OSwiaXNzIjoic3RyZWFrbHkiLCJhdWQiOiJzdHJlYWtseS1hcGkifQ.-VDoKUbNwY1pzp9sbTKyLatvUhg7Ko3_4xIklKs7teY

# Fill after GET /profile/me:
@userId = 4ce10efb-1037-454e-9b40-3bd6cca89c87

# ActivityID
@activityId = 82456f58-b5be-43b1-9a1b-cd84b182052a

# 1) Register a test user (201 Created)
POST {{host}}/auth
Content-Type: application/json

{
  "email": "{{email}}",
  "username": "{{username}}",
  "password": "{{password}}",
  "fullName": "{{fullName}}",
  "role": "{{role}}"
}

###

# 2) Sign in (200 OK) -> copy the accessToken to accessToken variable
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

# 3) Get user profile (200 OK) -> copy the id to userId variable
GET {{host}}/profile/me
Authorization: Bearer {{accessToken}}

###

# 4) Add activity without token (401 Unauthorized expected)
POST {{host}}/activity/addActivity/{{userId}}
Content-Type: application/json

{
  "userId": {
    "value": "{{userId}}"
  },
  "id": "11111111-1111-1111-1111-111111111111",
  "name": {
    "value": "Read 20 pages"
  },
  "description": {
    "value": "Daily reading routine"
  },
  "createdAt": "2026-03-06T10:00:00Z",
  "updatedAt": null,
  "startDate": "2026-03-06T10:00:00Z",
  "endDate": "2026-03-20T10:00:00Z",
  "frequencyType": 1,
  "completed": false
}

###

# 5) Add activity with token (success expected after handler implementation)
POST {{host}}/activity/addActivity/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "userId": {
    "value": "{{userId}}"
  },
  "id": "22222222-2222-2222-2222-222222222222",
  "name": {
    "value": "Run 555 km"
  },
  "description": {
    "value": "Cardio training_test"
  },
  "createdAt": "2026-03-06T10:00:00Z",
  "updatedAt": null,
  "startDate": "2026-03-06T10:00:00Z",
  "endDate": "2026-03-20T10:00:00Z",
  "frequencyType": 1,
  "completed": false
}

###

# 6) Delete Activity
DELETE {{host}}/activity/deleteActivity
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{activityId}}"
}

###

# 7) Set Activity as completed
PATCH {{host}}/activity/markAsCompleted
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{activityId}}"
}

###

# 8) Set Activity as incompleted
PATCH {{host}}/activity/markAsIncompleted
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{activityId}}"
}

###

# 9) Change Activity name
PATCH {{host}}/activity/changeActivityName
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{activityId}}",
  "newActivityName": "updated_activity_name"
}

###

# 10) Change Activity description
PATCH {{host}}/activity/changeActivityDescription
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "{{activityId}}",
  "newActivityDescription": "updated_activity_description"
}

###

### 11) Get Activity
GET {{host}}/activity/{{activityId}}
Authorization: Bearer {{accessToken}}
Accept: application/json
