@url = http://localhost:5185
@randomGuid = de305d54-75b4-431b-adb2-eb6b9e546014
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNDVhYWYxNi00YWNiLTQ3ZDMtYTljNS0zNzc0ZTY1NzJlYzgiLCJ1bmlxdWVfbmFtZSI6IjA0NWFhZjE2LTRhY2ItNDdkMy1hOWM1LTM3NzRlNjU3MmVjOCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJuYmYiOjE3NzI1NDE1NTYsImV4cCI6MTc3MjU0NTE1NiwiaXNzIjoic3RyZWFrbHkiLCJhdWQiOiJzdHJlYWtseS1hcGkifQ.azrlpinPrUKc3QgeesHFRczpPKKQ5R1mMfq-PMV10xA


### Users: Get User by Id
GET {{url}}/users/{{randomGuid}}

### Users: Add sample User
POST {{url}}/auth
Content-Type: application/json

{
  "email": "test@test.com",
  "username": "tester",
  "password": "123456789",
  "fullName": "John Doe",
  "role": "user"
}

### Users: Sign in
POST {{url}}/auth/sign-in
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456789"
}

### Profile: Get me
GET {{url}}/profile/me
Authorization: Bearer {{accessToken}}

### Users: Get all Users (list of UserDtos)
GET {{url}}/users/all

### Users: Delete User (paste in UserId)
DELETE {{url}}/users/05f7bb2f-c4ee-4993-9795-475d7e49d1b5

### Profile: Change Username
PATCH {{url}}/profile/me/changeUsername
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "newUsername": "updated_username"
}

### Profile: Change Fullname
PATCH {{url}}/profile/me/changeFullname
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "newFullname": "updated_fullname"
}