@url = http://localhost:5185
@randomGuid = de305d54-75b4-431b-adb2-eb6b9e546014

###
GET {{url}}/users/{{randomGuid}}

###
POST {{url}}/users
Content-Type: application/json

{
  "email": "test@test.com",
  "username": "tester",
  "password": "123456789",
  "fullName": "John Doe",
  "role": "user"
}

###
GET {{url}}/users/all


